### ISSUE TITLE
Development `npm start` fails.

### ISSUE THREAD

**Issue by vanboom** [sweetalert2/sweetalert2#1019]
Following the dev/contributing guidelines, after a successful `npm install`, `npm start` fails...

```
> sweetalert2@7.15.1 start /data/gems/sweetalert2
> gulp develop --continue-on-lint-error --skip-minification --skip-standalone

/data/gems/sweetalert2/gulpfile.js:32
gulp.task('clean', async () => {
                         ^

SyntaxError: Unexpected token (
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:374:25)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at execute (/data/gems/sweetalert2/node_modules/gulp/node_modules/gulp-cli/lib/versioned/^4.0.0-alpha.2/index.js:36:18)
    at Liftoff.handleArguments (/data/gems/sweetalert2/node_modules/gulp/node_modules/gulp-cli/index.js:175:63)
    at Liftoff.execute (/data/gems/sweetalert2/node_modules/liftoff/index.js:203:12)

npm ERR! Linux 4.4.0-116-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "start"
npm ERR! node v4.2.6
npm ERR! npm  v3.5.2
npm ERR! code ELIFECYCLE
npm ERR! sweetalert2@7.15.1 start: `gulp develop --continue-on-lint-error --skip-minification --skip-standalone`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the sweetalert2@7.15.1 start script 'gulp develop --continue-on-lint-error --skip-minification --skip-standalone'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the sweetalert2 package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     gulp develop --continue-on-lint-error --skip-minification --skip-standalone
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs sweetalert2
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls sweetalert2
npm ERR! There is likely additional logging output above.

```

**Comment by vanboom** [comment]
I had an old version of node and used this guide to update: https://askubuntu.com/questions/426750/how-can-i-update-my-nodejs-to-the-latest-version
