### ISSUE TITLE
AoT build failed on production mode with new Angular 6

### ISSUE THREAD

**Issue by vincent-cm** [sweetalert2/sweetalert2#1101]
Package installed

    "@toverux/ngx-sweetalert2": "^3.4.0",
    "sweetalert2": "^7.20.6",

with angular:

    "@angular/animations": "^6.0.2",
    "@angular/cdk": "^6.0.2",
    "@angular/common": "^6.0.2",
    "@angular/compiler": "^6.0.2",
    "@angular/core": "^6.0.2",
    "@angular/forms": "^6.0.2",
    "@angular/http": "^6.0.2",
    "@angular/material": "^6.0.2",
    "@angular/platform-browser": "^6.0.2",
    "@angular/platform-browser-dynamic": "^6.0.2",
    "@angular/platform-server": "^6.0.2",
    "@angular/router": "^6.0.2",

    "@angular-devkit/build-optimizer": "^0.6.3",
    "@angular/cli": "^6.0.3",
    "@angular/compiler-cli": "^6.0.2",
    "@angular/language-service": "^6.0.2", 

Status: run dev mode to bundle with webpack is works well, but failed with production mode
All I use is: ng serve vs ng build --prod

Error message:

```
ERROR in ./node_modules/sweetalert2/dist/sweetalert2.all.js
Module build failed: RangeError: Maximum call stack size exceeded
    at computeLineAndCharacterOfPosition (/Project/node_modules/typescript/lib/typescript.js:6093:47)
    at Object.getLineAndCharacterOfPosition (/Project/node_modules/typescript/lib/typescript.js:6113:16)
    at getLineOfLocalPosition (/Project/node_modules/typescript/lib/typescript.js:10262:19)
    at positionsAreOnSameLine (/Project/node_modules/typescript/lib/typescript.js:10978:13)
    at Object.rangeEndIsOnSameLineAsRangeStart (/Project/node_modules/typescript/lib/typescript.js:10973:16)
    at needsIndentation (/Project/node_modules/typescript/lib/typescript.js:73203:24)
    at emitBinaryExpression (/Project/node_modules/typescript/lib/typescript.js:71844:40)
    at pipelineEmitExpression (/Project/node_modules/typescript/lib/typescript.js:71317:28)
    at pipelineEmitWithHint (/Project/node_modules/typescript/lib/typescript.js:70991:49)
    at emitNodeWithSourceMap (/Project/node_modules/typescript/lib/typescript.js:68279:21)
    at pipelineEmitWithSourceMap (/Project/node_modules/typescript/lib/typescript.js:70981:17)
    at emitNodeWithNestedComments (/Project/node_modules/typescript/lib/typescript.js:68568:17)
    at emitNodeWithSynthesizedComments (/Project/node_modules/typescript/lib/typescript.js:68518:13)
    at emitNodeWithComments (/Project/node_modules/typescript/lib/typescript.js:68488:21)
    at pipelineEmitWithComments (/Project/node_modules/typescript/lib/typescript.js:70973:17)
    at emitNodeWithNotification (/Project/node_modules/typescript/lib/typescript.js:67902:21)
    at pipelineEmitWithNotification (/Project/node_modules/typescript/lib/typescript.js:70964:17)
    at emitExpression (/Project/node_modules/typescript/lib/typescript.js:70960:13)
    at emitBinaryExpression (/Project/node_modules/typescript/lib/typescript.js:71846:13)
    at pipelineEmitExpression (/Project/node_modules/typescript/lib/typescript.js:71317:28)
    at pipelineEmitWithHint (/Project/node_modules/typescript/lib/typescript.js:70991:49)
    at emitNodeWithSourceMap (/Project/node_modules/typescript/lib/typescript.js:68279:21)
    at pipelineEmitWithSourceMap (/Project/node_modules/typescript/lib/typescript.js:70981:17)
    at emitNodeWithNestedComments (/Project/node_modules/typescript/lib/typescript.js:68568:17)
    at emitNodeWithSynthesizedComments (/Project/node_modules/typescript/lib/typescript.js:68518:13)
    at emitNodeWithComments (/Project/node_modules/typescript/lib/typescript.js:68488:21)
    at pipelineEmitWithComments (/Project/node_modules/typescript/lib/typescript.js:70973:17)
    at emitNodeWithNotification (/Project/node_modules/typescript/lib/typescript.js:67902:21)
    at pipelineEmitWithNotification (/Project/node_modules/typescript/lib/typescript.js:70964:17)
    at emitExpression (/Project/node_modules/typescript/lib/typescript.js:70960:13)
    at emitBinaryExpression (/Project/node_modules/typescript/lib/typescript.js:71846:13)
    at pipelineEmitExpression (/Project/node_modules/typescript/lib/typescript.js:71317:28)
    at pipelineEmitWithHint (/Project/node_modules/typescript/lib/typescript.js:70991:49)
    at emitNodeWithSourceMap (/Project/node_modules/typescript/lib/typescript.js:68279:21)
    at pipelineEmitWithSourceMap (/Project/node_modules/typescript/lib/typescript.js:70981:17)
    at emitNodeWithNestedComments (/Project/node_modules/typescript/lib/typescript.js:68568:17)
 @ ./node_modules/@toverux/ngx-sweetalert2/esm5/toverux-ngx-sweetalert2.js 1:0-31 6:42-46 7:44-48 8:51-55 9:44-48 10:50-54 11:49-53 12:43-47 34:26-30 63:12-16 77:22-26 111:35-39
 @ ./node_modules/@toverux/ngx-sweetalert2/toverux-ngx-sweetalert2.ngfactory.js
 @ ./src/app/app.module.ngfactory.js
 @ ./src/main.browser.ts
```

**Comment by limonte** [comment]
Duplicate of https://github.com/sweetalert2/ngx-sweetalert2/issues/69

**Comment by vincent-cm** [comment]
@limonte I consider it is not a dup of not supporting ng6. Actually, it works well on AoT without production build.

**Comment by limonte** [comment]
@vincent-cm whatever it is, this is the right place for ng-related issues: https://github.com/sweetalert2/ngx-sweetalert2

**Comment by toverux** [comment]
Please install latest 4.0.0 build, it may fix your problem (I can't reproduce it with this version).

**Comment by vincent-cm** [comment]
@toverux Did you tried to build AoT for production? It is working in dev mode only in my setting.

**Comment by nuvoPoint** [comment]
We have the same issue, but it will work if you turn off sourcemaps in production - which is not optimal in our setup.

**Comment by mattrenaud** [comment]
For anyone coming here that is still having this issue with source maps, here is my assessment: `typescript` is throwing up while parsing the massive css concatenation at the end of the `sweetalert2.all.js` file. Because if the size of the expression, the process is tipped over the edge of its call stack limits. I noticed some people get this issue and some don't. I believe this is because the amount of data the stack takes up is dependent on many factors: OS, project setup, environment, etc. I found that two things work around the problem:

1) Import the styles and js separately as described in the [README.md](https://github.com/sweetalert2/sweetalert2/blob/master/README.md)

> It's possible to import JS and CSS separately, e.g. if you need to customize styles:
> 
> ```js
> import swal from 'sweetalert2/dist/sweetalert2.js'
> 
> import 'sweetalert2/src/sweetalert2.scss'
> ```

2) A less savory approach is to increase the default stack size in node temporarily when doing a build. Something like:

**NOTE: BE CAREFUL WITH THIS!!**

`$ node --stack_size=1968 ./node_modules/.bin/ng build --prod`

I'm on MacOS and used `$ ulimit -a` to make sure I was under the system limit. You may want to do something similar. Otherwise you may get segmentation faults.

If you are using `ngx-sweetalert2` or something similar you may have to go with 2) or fork the repo and patch 1) yourself until it is fixed.
