### ISSUE TITLE
Cancelling an alert after clicking Ok on a different alert gives an error: Cannot read properties of undefined (reading 'confirmButton')

### ISSUE THREAD

**Issue by scottieslg** [sweetalert2/sweetalert2#2569]
I have 2 Sweetalerts in my page, and if I trigger the first one, and the user clicks "Ok", then I trigger the second one and the user clicks "Cancel", I get an error "Cannot read properties of undefined (reading 'confirmButton')"

First sweetalert:

```
const result = await Swal.fire({
	icon: 'question',
	title: 'Add New Aisle',
	text: `Aisle ${text} was not found.  Do you wish to add it?`,
	confirmButtonColor: '#007bff',
	showCancelButton: true,
	width: '28em',
	heightAuto: false
});
```

Second one:
```	
const result = await Swal.fire({
		icon: 'question',
		title: 'Add New Area',
		text: `Area ${text} was not found.  Do you wish to add it?`,
		confirmButtonColor: '#007bff',
		showCancelButton: true,
		width: '28em',
		heightAuto: false
	});
```

Full error:
```
TypeError: Cannot read properties of undefined (reading 'confirmButton')
    at sweetalert2.all.js:3121:15
    at Array.forEach (<anonymous>)
    at setButtonsDisabled (sweetalert2.all.js:3120:13)
    at SweetAlert.disableButtons (sweetalert2.all.js:3146:5)
    at handleCancelButtonClick (sweetalert2.all.js:3344:14)
    at domCache.cancelButton.onclick [as __zone_symbol__ON_PROPERTYclick] (sweetalert2.all.js:3821:45)
    at HTMLButtonElement.wrapFn (zone.js:763:39)
    at ZoneDelegate.invokeTask (zone.js:406:31)
    at Object.onInvokeTask (core.mjs:26278:33)
    at ZoneDelegate.invokeTask (zone.js:405:60)
```

**Comment by limonte** [comment]
Please follow the issue template when reporting issues.

![image](https://user-images.githubusercontent.com/6059356/66860984-cc1b8800-ef96-11e9-8f5f-107553d403bf.png)
