### ISSUE TITLE
Unable to use with jsbin without defined body tag

### ISSUE THREAD

**Issue by limonte** [sweetalert2/sweetalert2#810]
Doesn't work: https://jsbin.com/sacaye/1/edit

Works nicely: https://jsbin.com/fifeye/1/edit

The error:

```
"TypeError: Cannot read property 'querySelector' of null
    at getContainer (https://unpkg.com/sweetalert2@7.3.5/dist/sweetalert2.all.js:1660:24)
    at getPopup (https://unpkg.com/sweetalert2@7.3.5/dist/sweetalert2.all.js:1664:10)
    at setParameters (https://unpkg.com/sweetalert2@7.3.5/dist/sweetalert2.all.js:246:18)
    at sweetAlert (https://unpkg.com/sweetalert2@7.3.5/dist/sweetalert2.all.js:652:3)
    at sacaye.js:1:309"
```

The related code: https://github.com/sweetalert2/sweetalert2/blob/3b61f1769c206010cb2b43a2cfcf7fcd9a2afb09/src/utils/dom.js#L124

**Comment by birjolaxew** [comment]
This is because JSBin places the "JavaScript" code in the `<head>` if there is no `<body>`, so it is ran before the DOM is loaded. It is not a problem with SweetAlert2.

**Comment by limonte** [comment]
> This is because JSBin places the "JavaScript" code in the <head> if there is no <body>, so it is ran before the body is loaded into the DOM. It is not a problem with SweetAlert2.

Agree, reported the issue to jsbin https://github.com/jsbin/jsbin/issues/3190

Nothing to fix on SweetAlert2's side.
